on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

name: CI

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - uses: bahmutov/npm-install@v1
      - name: Generate build artifact
        run: yarn build

      - name: Store artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-dist
          path: dist
          retention-days: 1

  build-site:
    name: Build Site
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build-dist
          path: dist

      - uses: bahmutov/npm-install@v1
      - name: Prepare linked dependency
        run: yarn link

      - uses: bahmutov/npm-install@v1
        with:
          working-directory: site

      - name: Link dependency
        run: yarn link vite-plugin-sloth
        working-directory: site

      - name: Build site to static
        run: yarn build
        working-directory: site

      - name: Validate build output
        run: yarn test

      - uses: actions/upload-artifact@v2
        with:
          name: site-dist
          path: site/dist
